apiVersion: v1
kind: Namespace
metadata:
  name: test-porkbun
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-noah-hood-io
  namespace: test-porkbun
spec:
  secretName: test-noah-hood-io-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "test.noah-hood.io"
