apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-noah-hood
  namespace: default
spec:
  secretName: test-noah-hood-tls
  issuerRef:
    name: porkbun-issuer
    kind: ClusterIssuer
  dnsNames:
    - test.noah-hood.io