apiVersion: v1
kind: ServiceAccount
metadata:
  name: porkbun-webhook
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-webhook
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-webhook
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porkbun-webhook:apiserver-authentication-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["extension-apiserver-authentication"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porkbun-webhook:apiserver-authentication-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: porkbun-webhook:apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-porkbun:webhook
rules:
- apiGroups: ["acme.noah-hood.io"]
  resources: ["porkbun-solvers", "porkbun-solver"]
  verbs: ["create", "get", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-porkbun:webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-porkbun:webhook
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager